services:
  traefik:
    image: traefik:3.7
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    environment:
      - TZ=Europe/Moscow
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - MAIN_DOMAIN=${MAIN_DOMAIN}
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"

      # Certificate Resolver (Cloudflare)
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
#      - "--certificatesresolvers.local.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"

      # API & Dashboard 
      - "--api.dashboard=false"
      - "--api.insecure=false"

#      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=60"
#      - "--certificatesresolvers.cloudflare.acme.dnschallenge.disablepropagationcheck=false"

      # Observability 
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    labels:
      - traefik.enable=false

#      - traefik.http.routers.dashboard.rule=Host(`traefik.${MAIN_DOMAIN}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
#      - traefik.http.routers.dashboard.entrypoints=websecure
#      - traefik.http.routers.dashboard.service=api@internal
#      - traefik.http.routers.dashboard.tls=true
#      - traefik.http.routers.dashboard.tls.certresolver=cloudflare

      # Basic‑auth middleware
#      - traefik.http.routers.dashboard.middlewares=dashboard-auth
#      - traefik.http.middlewares.dashboard-auth.basicauth.users=${PASSWORD_HASH}
    ports:
      - 443:443
      - 80:80
    networks:
      - proxy

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=false
#      - traefik.http.routers.whoami.rule=Host(`whoami.${MAIN_DOMAIN}`)
#      - traefik.http.routers.whoami.entrypoints=websecure
#      - traefik.http.routers.whoami.tls=true
#      - traefik.http.routers.whoami.tls.certresolver=cloudflare

  matrae:
    image: ghcr.io/mizuchilabs/mantrae:0.8.9
    container_name: mantrae
    restart: unless-stopped
    environment:
      - SECRET=${MANTRAE_SECRET}
      - ADMIN_PASSWORD=${MANTRAE_ADMIN_PASSWORD}
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
    volumes:
      - ./mantrae-data:/data
    labels:
      - traefik.enable=true

      - traefik.http.routers.mantrae.rule=Host(`mantrae.${MAIN_DOMAIN}`)
      - traefik.http.routers.mantrae.entrypoints=websecure
      - traefik.http.routers.mantrae.tls=true
      - traefik.http.routers.mantrae.tls.certresolver=cloudflare
      - traefik.http.services.mantrae.loadbalancer.server.port=3000
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
    driver_opts:
      com.docker.network.dns.mtu: 1500
